export default () => [
  <link
    key="0"
    rel="apple-touch-icon"
    sizes="57x57"
    href="/static/home/icons/apple-icon-57x57.png"
  />,
  <link
    key="1"
    rel="apple-touch-icon"
    sizes="60x60"
    href="/static/home/icons/apple-icon-60x60.png"
  />,
  <link
    key="2"
    rel="apple-touch-icon"
    sizes="72x72"
    href="/static/home/icons/apple-icon-72x72.png"
  />,
  <link
    key="3"
    rel="apple-touch-icon"
    sizes="76x76"
    href="/static/home/icons/apple-icon-76x76.png"
  />,
  <link
    key="4"
    rel="apple-touch-icon"
    sizes="114x114"
    href="/static/home/icons/apple-icon-114x114.png"
  />,
  <link
    key="15"
    rel="apple-touch-icon"
    sizes="120x120"
    href="/static/home/icons/apple-icon-120x120.png"
  />,
  <link
    key="5"
    rel="apple-touch-icon"
    sizes="144x144"
    href="/static/home/icons/apple-icon-144x144.png"
  />,
  <link
    key="6"
    rel="apple-touch-icon"
    sizes="152x152"
    href="/static/home/icons/apple-icon-152x152.png"
  />,
  <link
    key="7"
    rel="apple-touch-icon"
    sizes="180x180"
    href="/static/home/icons/apple-icon-180x180.png"
  />,
  <link
    key="8"
    rel="icon"
    type="image/png"
    sizes="192x192"
    href="/static/home/icons/android-icon-192x192.png"
  />,
  <link
    key="9"
    rel="icon"
    type="image/png"
    sizes="32x32"
    href="/static/home/icons/favicon-32x32.png"
  />,
  <link
    key="10"
    rel="icon"
    type="image/png"
    sizes="96x96"
    href="/static/home/icons/favicon-96x96.png"
  />,
  <link
    key="11"
    rel="icon"
    type="image/png"
    sizes="16x16"
    href="/static/home/icons/favicon-16x16.png"
  />,
  <meta key="12" name="msapplication-TileColor" content="#ffffff" />,
  <meta
    key="13"
    name="msapplication-TileImage"
    content="/static/home/icons/ms-icon-144x144.png"
  />,
  <meta key="14" name="theme-color" content="#ffffff" />
];
